import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { LoginComponent } from './components/login/login.component';
import { SignupComponent } from './components/signup/signup.component';
import { AddMatchComponent } from './components/add-match/add-match.component';
import { AddPlayerComponent } from './components/add-player/add-player.component';
import { AddTeamComponent } from './components/add-team/add-team.component';
import { ResultComponent } from './components/result/result.component';
import { MatchesComponent } from './components/matches/matches.component';
import { AdminComponent } from './components/admin/admin.component';
import { MatchInfoComponent } from './components/match-info/match-info.component';
import { EditMatchComponent } from './components/edit-match/edit-match.component';
import { PlayersComponent } from './components/players/players.component';
import { TeamsComponent } from './components/teams/teams.component';
import { TeamInfoComponent } from './components/team-info/team-info.component';
import { EditTeamComponent } from './components/edit-team/edit-team.component';
import { PlayerInfoComponent } from './components/player-info/player-info.component';
import { EditPlayerComponent } from './components/edit-player/edit-player.component';
import { AddStadiumComponent } from './components/add-stadium/add-stadium.component';
import { SearchMatchesComponent } from './components/search-matches/search-matches.component';
import { StadiumsComponent } from './components/stadiums/stadiums.component';
import { StadiumInfoComponent } from './components/stadium-info/stadium-info.component';
import { EditStadiumComponent } from './components/edit-stadium/edit-stadium.component';

export const routes: Routes = [
    {path : "", component : HomeComponent},
    {path : "login", component : LoginComponent},
    {path : "signup", component : SignupComponent},
    {path : "signupAdmin", component : SignupComponent},
    {path : "addMatch", component : AddMatchComponent},
    {path : "addPlayer", component : AddPlayerComponent},
    {path : "addTeam", component : AddTeamComponent},
    {path : "addStadium", component : AddStadiumComponent},
    {path : "result", component : ResultComponent},
    {path : "matches", component : MatchesComponent},
    {path : "admin", component : AdminComponent},
    {path : "matchInfo/:id", component : MatchInfoComponent},
    {path : "editMatch/:id", component : EditMatchComponent},
    {path : "players", component : PlayersComponent},
    {path : "teams", component : TeamsComponent},
    {path : "teamInfo/:id", component : TeamInfoComponent},
    {path : "editTeam/:id", component : EditTeamComponent},
    {path : "playerInfo/:id", component : PlayerInfoComponent},
    {path : "editPlayer/:id", component : EditPlayerComponent},
    {path : "searchMatch", component : SearchMatchesComponent},
    {path : "stadiums", component : StadiumsComponent},
    {path : "stadiumInfo/:id", component : StadiumInfoComponent},
    {path : "editStadium/:id", component : EditStadiumComponent},

];
    